// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQMVdSFvtd6P4z9BlN9qcCT62-fHUJDPQ',
    appId: '1:153679250267:web:4e87c6888ec537ebb3d07e',
    messagingSenderId: '153679250267',
    projectId: 'destinytravel-1a16e',
    authDomain: 'destinytravel-1a16e.firebaseapp.com',
    storageBucket: 'destinytravel-1a16e.firebasestorage.app',
    measurementId: 'G-0TXEHZK0DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx1yxgZJHvysC2QxaCsSIdJtUVr_rsFRk',
    appId: '1:153679250267:android:f01f55255eabb4bbb3d07e',
    messagingSenderId: '153679250267',
    projectId: 'destinytravel-1a16e',
    storageBucket: 'destinytravel-1a16e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDth41dqhoxzLVUYkTJJmHEfC2XezyFVLQ',
    appId: '1:153679250267:ios:a41039fc09ca57cbb3d07e',
    messagingSenderId: '153679250267',
    projectId: 'destinytravel-1a16e',
    storageBucket: 'destinytravel-1a16e.firebasestorage.app',
    iosClientId: '153679250267-ae6ojjh32k60bn8e3o7juppid7applkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.destiny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDth41dqhoxzLVUYkTJJmHEfC2XezyFVLQ',
    appId: '1:153679250267:ios:a41039fc09ca57cbb3d07e',
    messagingSenderId: '153679250267',
    projectId: 'destinytravel-1a16e',
    storageBucket: 'destinytravel-1a16e.firebasestorage.app',
    iosClientId: '153679250267-ae6ojjh32k60bn8e3o7juppid7applkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.destiny',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQMVdSFvtd6P4z9BlN9qcCT62-fHUJDPQ',
    appId: '1:153679250267:web:34269b7abff14df0b3d07e',
    messagingSenderId: '153679250267',
    projectId: 'destinytravel-1a16e',
    authDomain: 'destinytravel-1a16e.firebaseapp.com',
    storageBucket: 'destinytravel-1a16e.firebasestorage.app',
    measurementId: 'G-GFNLESR7X5',
  );
}
